# Work in progress: using a commit hash from GitHub, as there's no tagged release yet
{% set version = "1.0.5" %}

package:
  name: reaktoro
  version: {{ version }}

source:
  url: https://github.com/reaktoro/reaktoro/archive/v{{ version }}.tar.gz
  sha256: 6751ae563bc328571922e105de180fb60aeae59b40afde0ddf81a6f7c545708e

build:
  number: 0
  skip: True  # [py2k or c_compiler == 'toolchain_c']

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.13
    - ninja
  host:
    - boost
    - invoke
    - numpy 1.14.*
    - pybind11
    - python
    - tabulate
  run:
    - boost
    - python
    - {{ pin_compatible('numpy') }}
test:
  imports:
    - reaktoro

about:
  home: http://github.com/reaktoro/reaktoro
  license: LGPL-2.1
  license_family: LGPL
  license_file: LICENSE
  summary: A unified framework for modeling chemically reactive systems
  description: |
    Reaktoro is a unified framework for modeling chemically reactive systems.
    It provides methods for chemical equilibrium and kinetic calculations
    for multiphase systems. Reaktoro is mainly developed in C++ for
    performance reasons. A Python interface is available for a more
    convenient and simpler use.
  doc_url: https://reaktoro.org
  dev_url: https://github.com/reaktoro/reaktoro

extra:
  recipe-maintainers:
    - allanleal
    - tadeu
    - nicoddemus
